POST http://localhost:8000/api/simulation?token=IUA2wRCjqO8xDgpD0vvoX4Cba-2VlIauGjzbwQaHlNI HTTP/1.1
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="01_linear_path.txt"
Content-Type: text/plain

< ../maps/hard/02_capacity_hell.txt
# < ../maps/medium/02_circular_loop.txt
--MfnBoundry--

###

GET http://localhost:8000/api/simulation?token=IUA2wRCjqO8xDgpD0vvoX4Cba-2VlIauGjzbwQaHlNI HTTP/1.1

###

GET http://localhost:8000/api/hubs?token=IUA2wRCjqO8xDgpD0vvoX4Cba-2VlIauGjzbwQaHlNI HTTP/1.1

###

GET http://localhost:8000/api/drones?token=IUA2wRCjqO8xDgpD0vvoX4Cba-2VlIauGjzbwQaHlNI HTTP/1.1

###

GET http://localhost:8000/api/connections?token=IUA2wRCjqO8xDgpD0vvoX4Cba-2VlIauGjzbwQaHlNI HTTP/1.1

###

POST http://localhost:8000/api/simulation/step?token=IUA2wRCjqO8xDgpD0vvoX4Cba-2VlIauGjzbwQaHlNI HTTP/1.1

###
GET http://localhost:8000/api/token