POST http://localhost:8000/api/simulation HTTP/1.1
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="01_linear_path.txt"
Content-Type: text/plain

< ../maps/hard/02_capacity_hell.txt
--MfnBoundry--
###

GET http://localhost:8000/api/simulation?token=aLFbH0WF9qt0wVIL5vUQ-Q3oIidKOveQRWU1dkfLCKI HTTP/1.1

###

POST http://localhost:8000/api/simulation/step?token=Q2Yk8CZW-95IRnmRm06cOYOsgXLuecomUR0AF-llhvI HTTP/1.1
